---
- hosts: all
  tasks:
    - name: check mariaDB status
      command: /usr/bin/systemctl is-active mariadb
      ignore_errors: yes
      register: result


    - name: install http if mariadb is active
      yum:
        name: httpd
        state: latest
      when: result.rc == 0


    - name: start http
      service:
        name: httpd
        state: started
