---
- name: add in boot paramter
  hosts: controller.example.com
  tasks:
  - name: modify grub option
    lineinfile:
      path: /etc/default/grub
      regexp: "^GRUB_CMDLINE_LINUX"
      line: 'GRUB_CMDLINE_LINUX="console=ttyS0,115200n8 no_timer_check net.ifnames=0 nvme_core.io_timeout=4294967295 nvme_core.max_retries=10 crashkernel=auto net.ifnames=0 biosdevname=0"'
  - name: rebuild grub
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
